#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChatAppTdd.Droid.Resource", IsApplication=true)]

namespace ChatAppTdd.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int colorAccentMain = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int colorBlack = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int colorDarkBlueGray = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int colorLightBlueGray = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int colorMediumBlueGray = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int colorWhite = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int authBtn = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int langSwitch = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int loginField = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int loginLabelTxt = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int passwordField = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int passwordLabelTxt = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int registerBtn = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int textView = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int textView2 = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuthorizationLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RegistrationLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int auth_btn_text_default = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int login_btn_text_default = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int login_lbl_text_default = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int password_lbl_text_default = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
